project:
  name: BirdCLEF+ 2025
  description: Multi-species acoustic monitoring in El Silencio Natural Reserve, Colombia

paths:
  data:
    raw: data/raw/
    processed: data/processed/
    interim: data/interim/
  models: outputs/models/
  submissions: outputs/submissions/

audio:
  sample_rate: 32000  # Competition uses 32 kHz
  audio_length: 5  # 5-second segments for evaluation
  n_mels: 128
  n_fft: 1024
  hop_length: 512
  fmin: 50   # Lower frequency boundary in Hz
  fmax: 16000  # Upper frequency boundary in Hz

training:
  seed: 42
  batch_size: 32
  num_epochs: 30
  learning_rate: 0.001
  patience: 5
  num_workers: 4
  use_weighted_loss: true
  weight_decay: 1e-5
  scheduler: one_cycle  # options: reduce_on_plateau, one_cycle
  use_adam: true  # false will use SGD with momentum
  
augmentation:
  use_mixup: true
  mixup_alpha: 0.2
  use_specaugment: true
  use_strong_augmentation: true
  use_background_noise: true
  use_taxonomic_augmentation: true

features:
  use_taxonomic_features: true
  use_advanced_features: true
  feature_ensemble: true  # Use multiple feature representations
  mel_spectrogram:
    enabled: true
    n_mels: 128
  mfcc:
    enabled: true
    n_mfcc: 20
  chroma:
    enabled: false
  spectral_contrast:
    enabled: true

models:
  architectures:
    - efficientnet
    - attention
  ensemble_weights:
    efficientnet: 1.0
    attention: 1.0
    
taxonomic:
  enable_taxonomic_training: true
  class_specific_thresholds:
    Aves: 0.3
    Amphibia: 0.4
    Insecta: 0.4
    Mammalia: 0.35

semi_supervised:
  enable: true
  confidence_threshold: 0.5
  pseudo_label_weight: 0.5
  consistency_training: true

validation:
  stratified_sampling: true
  n_folds: 5

post_processing:
  temporal_smoothing: true
  smoothing_window: 3
  species_correlation_matrix: true  # Use co-occurrence patterns